### ISSUE TITLE
MANIFEST download failing after failed run

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#513]
2018-03-13 21:11:06,966 DEBUG   ./wpt:stderr INFO:manifest:Skipping manifest download because existing file is recent
2018-03-13 21:11:06,966 DEBUG   ./wpt:stderr Traceback (most recent call last):
2018-03-13 21:11:06,966 DEBUG   ./wpt:stderr   File "./wpt", line 5, in <module>
2018-03-13 21:11:06,966 DEBUG   ./wpt:stderr     wpt.main()
2018-03-13 21:11:06,966 DEBUG   ./wpt:stderr   File "/home/wptrunner/web-platform-tests/tools/wpt/wpt.py", line 132, in main
2018-03-13 21:11:06,966 DEBUG   ./wpt:stderr     rv = script(*args, **kwargs)
2018-03-13 21:11:06,967 DEBUG   ./wpt:stderr   File "/home/wptrunner/web-platform-tests/tools/manifest/update.py", line 96, in run
2018-03-13 21:11:06,967 DEBUG   ./wpt:stderr     update_from_cli(**kwargs)
2018-03-13 21:11:06,967 DEBUG   ./wpt:stderr   File "/home/wptrunner/web-platform-tests/tools/manifest/update.py", line 41, in update_from_cli
2018-03-13 21:11:06,967 DEBUG   ./wpt:stderr     m = manifest.load(tests_root, path)
2018-03-13 21:11:06,967 DEBUG   ./wpt:stderr   File "/home/wptrunner/web-platform-tests/tools/manifest/manifest.py", line 225, in load
2018-03-13 21:11:06,968 DEBUG   ./wpt:stderr     rv = Manifest.from_json(tests_root, json.load(f))
2018-03-13 21:11:06,968 DEBUG   ./wpt:stderr   File "/usr/lib/python2.7/json/__init__.py", line 291, in load
2018-03-13 21:11:06,969 DEBUG   ./wpt:stderr     **kw)
2018-03-13 21:11:06,969 DEBUG   ./wpt:stderr   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
2018-03-13 21:11:06,969 DEBUG   ./wpt:stderr     return _default_decoder.decode(s)
2018-03-13 21:11:06,969 DEBUG   ./wpt:stderr   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
2018-03-13 21:11:06,971 DEBUG   ./wpt:stderr     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2018-03-13 21:11:06,971 DEBUG   ./wpt:stderr   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
2018-03-13 21:11:06,971 DEBUG   ./wpt:stderr     raise ValueError("No JSON object could be decoded")
2018-03-13 21:11:06,971 DEBUG   ./wpt:stderr ValueError: No JSON object could be decoded
Traceback (most recent call last):
  File "./run/run.py", line 599, in <module>
    main(args.platform_id, platform, args, config)
  File "./run/run.py", line 105, in main
    setup_wpt(config, logger)
  File "./run/run.py", line 375, in setup_wpt
    '%d from command %s' % (proc.returncode, command))
AssertionError: Got non-0 return code: 1 from command ['./wpt', 'manifest', '--work']

I removed it manually.

**Comment by jugglinmike** [comment]
We addressed this issue via the introduction of a Buildbot-driven infrastructure (see gh-522).
